### ISSUE TITLE
现阶段如何模拟登陆

### ISSUE THREAD

**Issue by Ziy1-Tan** [unbyte/are-u-ok#12]
本人想在写一个自用的打卡脚本，在登陆上遇到了问题：pc登陆打卡平台需要通过neu的统一身份认证，本人在这个地址下通过阻塞请求、保留log的方式均不能获取到真实请求地址，请问您在之前写script的过程中如何获取到统一身份认证的请求信息的？

**Comment by unbyte** [comment]
浏览器F12
